Fix missing comma in metrics.__init__
Without it from `tslearn.metrics import *` throws a `AttributeError: module 'tslearn.metrics' has no attribute 'lcss_path_from_metricctw_path'`